### ISSUE TITLE
引入后导致的第三方css冲突

### ISSUE THREAD

**Issue by LovesAsuna** [amphineko/atomicneko#36]
捣鼓了一个晚上，因为没什么webpack的知识所以这东西弄起来实在是头疼，把这个嵌入进博客后导致博客原有的css与项目引入的第三方库(猜测是fontawesome)冲突了，想用css-loader但前端实在是难顶只能向作者求助了，我妥协了＼( T﹏T )／

**Comment by amphineko** [comment]
你的描述还没有讲明白具体是什么样的冲突。

我暂且猜测是 `atomicneko` 的样式里和你的博客有同样的 class 名称，这可以通过一些类似 uglyify 之类变换 class 名称的方式暂时解决。进一步的话还可以使用 CSS modules 来从根源上消除这个问题。

**Comment by LovesAsuna** [comment]
我猜是atomicneko里面用的fontawesome的class名称冲突，然后我就是研究css module来着，但是启用了module后不会引入到html里，单纯只是生成了hash之后的class

**Comment by LovesAsuna** [comment]
按照官方的说法，是用了style-loader+css-loader，把css作为js的模块来导出，但这种方法适用于anglar这种内容解析的框架，纯html只能靠js一个一个拼接，而且昨晚我的尝试是连拼接都报错 (前端太顶了，所以我觉得我自己是搞不定了

**Comment by amphineko** [comment]
https://github.com/amphineko/atomicneko/blob/594d3078355294e783e7746bc277bc2b5ac48b8c/src/index.html#L5

如果我对这个项目的印象没有错的话，这里会直接在 HTML 中 import index.css，也就是我提到的在 HTML 引入的方式。

**Comment by LovesAsuna** [comment]
是的，但通过css-module处理后，即使引用了但也由于hash之后跟html不一致，我主要就是想解决html里class能动态与hash之后的class保持一致，但是通过js写太过繁琐了

**Comment by amphineko** [comment]
关于这个问题，我没有什么快捷的解决方法可以提供给你。

- 你可以通过 source map 反射的方法把生成的 CSS 文件中对应的 class name 写回到 HTML 中。
- 你也可以把 `index.html` 转写成例如 React JSX 的档案，在其中导入 CSS modules，然后通过 Server-Side Rendering 的方法生成静态输出。

**Comment by amphineko** [comment]
另外如果你有使用 React 重写这个项目的计划的话，欢迎发 PR。

**Comment by LovesAsuna** [comment]
忘了有iframe这个玩意可以隔离了，直接可以无视冲突
